name: test_weather_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  calendar_time: ^2.0.0
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  geocoding: ^2.0.5
  geolocator: ^8.2.1
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  iconsax: ^0.0.8
  intl: ^0.17.0
  json_annotation: ^4.6.0
  retrofit: ^3.0.1+1
  timeago: ^3.3.0

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.2
  retrofit_generator: ^4.0.3+2

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  fonts:
    - family: OpenSauceSans
      fonts:
        - asset: assets/font/OpenSauceSans/OpenSauceSans-Regular.ttf
        - asset: assets/font/OpenSauceSans/OpenSauceSans-Italic.ttf
          style: italic
        - asset: assets/font/OpenSauceSans/OpenSauceSans-Light.ttf
          weight: 400
        - asset: assets/font/OpenSauceSans/OpenSauceSans-Medium.ttf
          weight: 600
        - asset: assets/font/OpenSauceSans/OpenSauceSans-SemiBold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
